name: Build Extension with Rates

on:
  schedule:
    - cron: '0 12 * * *'  # every day at 12:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # ensure you’re on main branch

      - name: Fetch Exchange Rates
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -s "https://openexchangerates.org/api/latest.json?app_id=$API_KEY" > data.json

      - name: Commit data.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes in data.json, skipping commit."
          else
            git commit -m "Update exchange rates [skip ci]"
            git push origin main
          fi

      - name: Package Extension
        run: |
          zip -r currency-converter.zip . -x ".git/*" "node_modules/*"

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: currency-converter
          path: currency-converter.zip
