name: Update Currency Rates

on:
  schedule:
    - cron: '0 14 * * *'  # 1st of each month at 00:00 UTC
  workflow_dispatch:

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to allow git operations
      
      - name: Fetch Rates
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/$API_KEY/latest/USD" > data.json
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          # Check if there are changes to commit
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update currency rates: $(date +'%Y-%m-%d')"
            git push
          fi
