name: Update Currency Rates

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Rates
        run: |
          # Fetch and add timestamp/attribution
          curl -s "https://api.exchangerate.host/latest?access_key=e03fcd7972217fa94ae33a8f73f27b27" | \
            jq '. + {disclaimer: "Data sourced from exchangerate.host", timestamp: (now | strftime("%Y-%m-%dT%H:%M:%SZ"))}' \
            > data.json

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update rates: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
