name: Fetch Exchange Rates Monthly

on:
  schedule:
    - cron: '0 0 1 * *'  # Runs at 00:00 UTC on the 1st of every month
  workflow_dispatch:      # Optional: Manually trigger the job

jobs:
  fetch-rates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch rates from ExchangeRate-API
        run: |
          API_URL="https://v6.exchangerate-api.com/v6/${{ secrets.API_KEY }}/latest/USD"
          curl -s "$API_URL" > data/rates.json

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/rates.json
          git commit -m "Update exchange rates (automated)"
          git push
