name: Update Currency Rates

on:
  schedule:
    - cron: '0 0 1 * *'  # 1st of each month
  workflow_dispatch:

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch Rates
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl -s "https://v6.exchangerate-api.com/v6/$API_KEY/latest/USD" > data.json
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          git commit -m "Update rates: $(date +'%Y-%m-%d')"
          git push
