name: Update Currency Rates

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-rates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Fetch Rates
        run: |
          # Fetch and transform the API response correctly
          curl -s "https://api.exchangerate.host/latest?base=USD" | \
            jq '{
              disclaimer: "Data sourced from exchangerate.host",
              timestamp: (.timestamp|todate),
              rates: .rates
            }' > data.json
          
          # Verify we got valid rates data
          if ! jq -e '.rates != null' data.json; then
            echo "Error: Failed to fetch rates - invalid response structure"
            cat data.json
            exit 1
          fi

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update rates: $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
            git push
          fi
